# Generated by Django 3.0.3 on 2020-09-09 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200909_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 8, 58, 59, 940631, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 8, 58, 59, 939620, tzinfo=utc)),
        ),
    ]
